server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    password: 
    url: jdbc:mysql://localhost:3306/portfoliodb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: email_adress
    password: email_app_password

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
